### ISSUE TITLE
PlaceholderAPI support

### ISSUE THREAD

**Issue by nisutec** [Avankziar/AdvanceEconomyPlus#2]
Hello,
Please add PlaceholderAPI support for this plugin.
https://github.com/PlaceholderAPI/PlaceholderAPI

**Comment by Avankziar** [comment]
Noted^^

**Comment by Avankziar** [comment]
All done^^
=> https://github.com/Avankziar/AdvanceEconomyPlus/wiki/ENG-PAPI
